---
title: "VR Consort Diagram"
author: "Brian Locke"
format: html
editor: visual
---

## Consort Diagram for VR ICU Project

Two \*.csv files exist: 1 for the entire requested data-set (including ambulatory, emergency, and inpatient encounters), and another for the post-processed dataset (including only encounters that have at least one of the expected data elements present - e.g. medications, vital signs, diagnoses, etc.)

## Consort Package

```{r}
#| echo: false
library(consort)
library(tidyverse)
library(medicaldata)
```

```{r}
library(haven)
library(dplyr)
library(rsvg)
library(DiagrammeRsvg)
library(magick)

# Read in the stata dataframe and apply the factor labels. 
vr_paper_data <- read_dta('/Users/blocke/Box Sync/Residency Personal Files/Scholarly Work/Locke Research Projects/VR in ICU/Data/db_for_consort.dta')

# Make NA's
vr_paper_data <- vr_paper_data %>%
  mutate(didnt_finish = na_if(didnt_finish, ""),
         reason_declined = na_if(reason_declined, ""))

# Add patient care need
vr_paper_data$no_survey <- NA  # Initialize the column with NA
vr_paper_data$no_survey[vr_paper_data$date == "2024-01-19"] <- "Time-sensitive patient care need"

p_cons = consort_plot(vr_paper_data,
             order = list(id    = "Patients approached",
                          reason_declined = "Declined to participate",
                          id = "Agreed to participate",
                          didnt_finish = "Did not start VR",
                          patient_id = "Completed VR experience",
                          no_survey = "Did not finish survey",
                          patient_id = "Completed all study assessments"),
             side_box = c("reason_declined", "didnt_finish", "no_survey"),
             cex = 1.3,
             text_width = 40)


plot(p_cons, grViz = TRUE) |> 
    DiagrammeRsvg::export_svg() |> 
    charToRaw() |> 
    rsvg::rsvg_png(file = "/Users/blocke/Box Sync/Residency Personal Files/Scholarly Work/Locke Research Projects/VR in ICU/Data/consort.png", width = 900, height = 1200)

# Code to use magick to designate DPI at 300 
image <- image_read("/Users/blocke/Box Sync/Residency Personal Files/Scholarly Work/Locke Research Projects/VR in ICU/Data/consort.png" )
image_write(image, path = "/Users/blocke/Box Sync/Residency Personal Files/Scholarly Work/Locke Research Projects/VR in ICU/Data/consort_dpi300.png", density = 300)



# p_cons
```
